// <auto-generated />
using System;
using ArtikelFinder.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArtikelFinder.Api.Data.Migrations
{
    [DbContext(typeof(ArtikelFinderDbContext))]
    [Migration("20260808161008_Produktangaben")]
    partial class Produktangaben
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Artikel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Allergene")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artikelnummer")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Auszeichnungen")
                        .HasColumnType("TEXT");

                    b.Property<string>("BildUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ean")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<long>("ErstelltAm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErstelltVon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<long?>("GeaendertAm")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Marke")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Menge")
                        .HasColumnType("TEXT");

                    b.Property<string>("Naehrwerte")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nutriscore")
                        .HasColumnType("TEXT");

                    b.Property<string>("Spuren")
                        .HasColumnType("TEXT");

                    b.Property<string>("SuchText")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("TEXT");

                    b.Property<string>("Zutaten")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Artikelnummer");

                    b.HasIndex("Ean")
                        .IsUnique()
                        .HasFilter("\"Ean\" IS NOT NULL");

                    b.HasIndex("KategorieId");

                    b.HasIndex("SuchText");

                    b.ToTable("Artikel");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Kategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentKategorieId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentKategorieId", "Name")
                        .IsUnique();

                    b.ToTable("Kategorien");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Markt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrundrissUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kette")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ort")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Strasse")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Maerkte");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Preis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtikelId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ErfasstAm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErfasstVon")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("MarktId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Werbepreis")
                        .HasColumnType("decimal(10,2)");

                    b.Property<long?>("WerbepreisGueltigBis")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("WerbepreisGueltigVon")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Wert")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MarktId");

                    b.HasIndex("ArtikelId", "MarktId", "ErfasstAm");

                    b.ToTable("Preise");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Standort", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtikelId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ErfasstAm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErfasstVon")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<float?>("KartenX")
                        .HasColumnType("REAL");

                    b.Property<float?>("KartenY")
                        .HasColumnType("REAL");

                    b.Property<int>("MarktId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RegalBeschreibung")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MarktId", "Gang");

                    b.HasIndex("ArtikelId", "MarktId", "ErfasstAm");

                    b.ToTable("Standorte");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Verlaufseintrag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aenderungsart")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ArtikelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Entitaet")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<long>("GeaendertAm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GeaendertVon")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArtikelId", "GeaendertAm");

                    b.ToTable("Verlauf");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Artikel", b =>
                {
                    b.HasOne("ArtikelFinder.Api.Entities.Kategorie", "Kategorie")
                        .WithMany("Artikel")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Kategorie", b =>
                {
                    b.HasOne("ArtikelFinder.Api.Entities.Kategorie", "ParentKategorie")
                        .WithMany("Unterkategorien")
                        .HasForeignKey("ParentKategorieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentKategorie");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Preis", b =>
                {
                    b.HasOne("ArtikelFinder.Api.Entities.Artikel", "Artikel")
                        .WithMany("Preise")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtikelFinder.Api.Entities.Markt", "Markt")
                        .WithMany("Preise")
                        .HasForeignKey("MarktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Markt");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Standort", b =>
                {
                    b.HasOne("ArtikelFinder.Api.Entities.Artikel", "Artikel")
                        .WithMany("Standorte")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArtikelFinder.Api.Entities.Markt", "Markt")
                        .WithMany("Standorte")
                        .HasForeignKey("MarktId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artikel");

                    b.Navigation("Markt");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Verlaufseintrag", b =>
                {
                    b.HasOne("ArtikelFinder.Api.Entities.Artikel", "Artikel")
                        .WithMany("Verlauf")
                        .HasForeignKey("ArtikelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikel");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Artikel", b =>
                {
                    b.Navigation("Preise");

                    b.Navigation("Standorte");

                    b.Navigation("Verlauf");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Kategorie", b =>
                {
                    b.Navigation("Artikel");

                    b.Navigation("Unterkategorien");
                });

            modelBuilder.Entity("ArtikelFinder.Api.Entities.Markt", b =>
                {
                    b.Navigation("Preise");

                    b.Navigation("Standorte");
                });
#pragma warning restore 612, 618
        }
    }
}
